import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./i18.js";
import { ThemeProvider } from "./ThemeContext/page";
import Footer from "@/footer/page";
import Navbar from "@/navbar/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uz">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <ThemeProvider>
          {<Navbar />}
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
